/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/need_some_space.glb --transform --keepnames 
Files: ./public/models/need_some_space.glb [1.4MB] > E:\KhoiDongDuAn\ManhTuan\warptalk-TestUI-web\need_some_space-transformed.glb [1.4MB] (0%)
Author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/need-some-space-d6521362b37b48e3a82bce4911409303
Title: Need some space?
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/need_some_space-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <points name="Object_2" geometry={nodes.Object_2.geometry} material={materials['Scene_-_Root']} rotation={[-Math.PI / 2, 0, 0]} scale={0.013} />
    </group>
  )
}

useGLTF.preload('/need_some_space-transformed.glb')
